### ISSUE TITLE
Дима я очень хочу сломать тебе колени, но не буду

### ISSUE THREAD

**Issue by mayerdev** [DimaCrafter/dc-api-core#23]
это сделает булочка

 ERR  Database driver "mongo" not registered
E:\Projects\swift\backend\node_modules\dc-api-core\session.js:20
        db.Session.deleteMany({ _id: { $lte: db._self.ObjectIdFromTime(Date.now() - config.session.ttl) } }).exec();
           ^

TypeError: Cannot read properties of undefined (reading 'Session')
    at cleanup (E:\Projects\swift\backend\node_modules\dc-api-core\session.js:20:12)
    at Object.<anonymous> (E:\Projects\swift\backend\node_modules\dc-api-core\session.js:23:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (E:\Projects\swift\backend\node_modules\dc-api-core\contexts\base.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
 ERR  API server process crushed with code 1

**Comment by mayerdev** [comment]
ты уже год не можешь пофиксить эту ошибку! я тебе реально обещаю, я рано или поздно вывезу тебя в лесополосу
