### ISSUE TITLE
Error: Cannot find module './uws_linux_x64_115.node' Node.js v20.9.0

### ISSUE THREAD

**Issue by whiteneofetch1** [DimaCrafter/dc-api-core#24]
20 нода нестабильная пока?

 npm run dev

> dc@1.0.0 dev
> dc-api-core --dev

API will be restarted after saving any file
You can submit `rs` to restart server manually

 INFO  Starting API...
/home/XXX/n/dc/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_115.node'
Require stack:
- /home/xxx/n/dc/node_modules/uWebSockets.js/uws.js
- /home/xxx/n/dc/node_modules/dc-api-core/index.js
    at /home/xxx/n/dc/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/home/xxx/n/dc/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xxx/n/dc/node_modules/dc-api-core/index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0
 ERR  API server process crushed with code 1

**Comment by DimaCrafter** [comment]
Для текущей версии uWS нет сборки под Node.js v20.
