### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Session')

### ISSUE THREAD

**Issue by mayerdev** [DimaCrafter/dc-api-core#25]
C:\Users\USER\Desktop\fh-backend\node_modules\dc-api-core\session.js:20
        db.Session.deleteMany({ _id: { $lte: db._self.ObjectIdFromTime(Date.now() - config.session.ttl) } }).exec();
           ^

TypeError: Cannot read properties of undefined (reading 'Session')
    at cleanup (C:\Users\USER\Desktop\fh-backend\node_modules\dc-api-core\session.js:20:12)
    at Object.<anonymous> (C:\Users\USER\Desktop\fh-backend\node_modules\dc-api-core\session.js:23:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (C:\Users\USER\Desktop\fh-backend\node_modules\dc-api-core\contexts\base.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
 ERR  API server process crushed with code 1
 
 ![2024-02-19 01 29 15](https://github.com/DimaCrafter/dc-api-core/assets/40364948/f154f45e-3ef6-4dac-8265-d7671268f117)

**Comment by mayerdev** [comment]
Node version: v16.20.1

**Comment by mayerdev** [comment]
Solution: `yarn add dc-api-core@next dc-api-mongo@next`
